### PR TITLE
Refactor/modularize

### PR DESCRIPTION
**Pull request by kebetsi**
Hi,
Would you be fine with this type of modularization?
I just followed Perki's idea on the [feature/hooks branch](https://github.com/pryv/dev-site/blob/feature/Hooks/source/_reference/data-structure/hook.coffee)

### CODE REVIEW

**Comment by sgoumaz** [comment]
Hi Ilia, not sure whom you were speaking to, but to me Yes, it's better this way, thanks.

Just one detail: is there a reason why we can't have `./data-structure/events` and the others directly export the data structure (instead of an object with a property like `event`)? (Then it would be renamed to the singular e.g. `./data-structure/event`)

**Comment by kebetsi** [comment]
Hi @sgoumaz,

Definitely, I thought about it as well.

**Comment by kschiess** [comment]
@kebetsi Can you either finish or close this?

**Comment by kschiess** [comment]
Stale PR, closing.

**Pull request closed without merging**
